service: server-env-config

custom:
  stage: ${opt:stage, 'DEV'}
  environment:
    MESSAGE:
      PROD: "This is production environment"
      DEV: "This is development environment"
      LOCAL: "This is local environment"
    SECRETS:
      DB: ${env:DB_${self:custom.stage}, file(local-secrets.yml):db}
      FIREBASE: ${env:FB_${self:custom.stage}, file(local-secrets.yml):firebase}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: eu-central-1
  environment:
    MESSAGE: ${self:custom.environment.MESSAGE.${self:custom.stage}}
    DB: ${self:custom.environment.SECRETS.DB}
    FIREBASE: ${self:custom.environment.SECRETS.FIREBASE}

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

functions:
  helloWorld:
    handler: src/handler.helloWorld
    events:
      - http:
          path: hello-world
          method: get
          cors: true
