version: 2
jobs:
  build:
    branches:
      only:
        - master
        - develop
    docker:
      - image: 'circleci/node:11.0.0'
    steps:
      - checkout
      - run:
          name: install yarn
          command: |
            sudo npm i -g yarn
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: |
            yarn
      - deploy:
          name: Production
          branch: 'master'
          command: yarn run deploy:prod
      - deploy:
          name: Develop
          branch: 'develop'
          command: yarn run deploy:dev
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
