version: 2
dependencies:
  cache_directories:
    - ~/.yarn-cache
  override:
    - yarn
jobs:
  build:
    branches:
      only:
        - master
        - develop
    docker:
      - image: 'circleci/node:11.0.0'
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: yarn
      - run:
          name: install serverless
          command: sudo yarn global add serverless --no-save     
      - deploy:
         name: deploy
         command: |
           if [ "${CIRCLE_BRANCH}" == "master" ]; then
             serverless deploy --verbose --stage PROD
           elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
             serverless deploy --verbose --stage DEV
           fi
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
